### ISSUE TITLE
Argument default value

### ISSUE THREAD

**Issue by gnugat** [memio/memio#17]
An `Argument` should be able to have a default value. It can be managed the same way `Constant` manages values: a raw string that will be directly printed in the template (allows to handle quotes for strings values, null, [numeric and string literals for PHP 5.6](http://php.net/manual/en/migration56.new-features.php), etc).

Adding `Argument#setDefaultValue` and `Argument#removeDefaultValue` is probably a good way to manage it.

**Comment by funivan** [comment]
I can implement this feature and suggest following logic
For all arguments allow set `NULL` `$arg->setDefaultValue(null);`
For object, callable, resource allow ONLY `NULL`

for objects:

``` php
$arg = new Argument('DateTime', 'date')
$arg->setDefaultValue(null); // = ok
$arg->setDefaultValue(''); // = ERROR
$arg->setDefaultValue('asd'); // = ERROR
```

for string:

``` php
$arg = new Argument('string', 'name')
$arg->setDefaultValue(null); // = ok
$arg->setDefaultValue(''); // = ok
$arg->setDefaultValue('asd'); // = ok
$arg->setDefaultValue(123); // = ERROR
```

And so on.

**Comment by gnugat** [comment]
I'd rather keep it simple and just give a string:

``` php
$arg->setDefaultValue('42'); // int
$arg->setDefaultValue("'nobody expects the spanish inquisition'"); // string
$arg->setDefaultValue('true'); // bool
$arg->setDefaultValue('null'); // NULL
$arg->setDefaultValue('self::MY_CONSTANT'); // constant
$arg->setDefaultValue('ONE + self::THREE'); // scalar expression involving numeric and string literals
```

**Comment by gnugat** [comment]
Would you like to work on this too?

**Comment by funivan** [comment]
Yes i can make it.
