### ISSUE TITLE
Class interfaces

### ISSUE THREAD

**Issue by gnugat** [memio/memio#20]
In PHP, a class can implement many interfaces.
This can be done by adding `Object#implement` and `Object#removeContract`.

**Comment by gnugat** [comment]
Currently blocked: waiting for #21

**Comment by gnugat** [comment]
No longer blocked!

**Comment by funivan** [comment]
Possible we can use following method names:

```
Object#addImplementation
Object#removeImplementation
Object#getImplementations
```

**Comment by gnugat** [comment]
It might be confusing: written this way we may think that the interface we add to the class is an implementation, when it is actually the other way around (a class implements an interface).

**Comment by gnugat** [comment]
Done.
