### ISSUE TITLE
Abstract methods

### ISSUE THREAD

**Issue by gnugat** [memio/memio#22]
Adding `Method#makeAbstract` and `Method#removeAbstract` could be a good way to manage method abstractness.

**Comment by funivan** [comment]
When we call `makeAbstract` we need to check if our method `isStatic` if true - throw exception
and vise versa
If method is abstract deny user to set it static.

**Comment by gnugat** [comment]
You're right, `Method` should definitely be responsible of checking its state, and making sure that it can't be static if it's abstract (and vis-versa).
We should probably create a `Gnugat\Medio\Exception\DomainException` class and throw it in those cases.

**Comment by funivan** [comment]
Ok. I can make this feature =)

**Comment by gnugat** [comment]
Thanks

**Comment by gnugat** [comment]
I'm counting on you for this one :)
