### ISSUE TITLE
Property default value

### ISSUE THREAD

**Issue by gnugat** [memio/memio#27]
In PHP, a property can have a default value.

**Comment by funivan** [comment]
I puprose following logic
For all arguments allow set `NULL` `$arg->setDefaultValue(null);`
For object, callable, resource allow ONLY `NULL`

for objects:
```php
$arg = new Argument('DateTime', 'date')
$arg->setDefaultValue(null); // = ok
$arg->setDefaultValue(''); // = ERROR
$arg->setDefaultValue('asd'); // = ERROR
```

for string:
```php
$arg = new Argument('string', 'name')
$arg->setDefaultValue(null); // = ok
$arg->setDefaultValue(''); // = ok
$arg->setDefaultValue('asd'); // = ok
$arg->setDefaultValue(123); // = ERROR
```
And so on.

**Comment by funivan** [comment]
Property default values it related to Argument default value
Possible it is better to create base class and extend it
It will give some pros
- Same interface 

```
(new Property('string', 'userName')->setDefaultValue('custom');
(new Argument('string', 'userName')->setDefaultValue('custom');
```
- According to this data we can create clean and useful phpdoc comments In methods and in property fields

**Comment by gnugat** [comment]
Well I'd rather favour composition over inheritance, if there's some logic to share between two classes.
But in this case, it's just a setter so it doesn't really make sense to try to refactor it.

**Comment by gnugat** [comment]
Done.
