### ISSUE TITLE
File.php bug with fullyQualifiedName

### ISSUE THREAD

**Issue by funivan** [memio/memio#28]
There is s bug in  `File.php` 
For example if we init file with path `Medio.php` is failure with error `Undefined offset: -1`

``` php
    $file = new File("Medio.php", Object::make('Test\\Medio'));
```

I thinks file path and `fullyQualifiedName` must be separated. 
Probably it is better to get fqdn from Struct class
If we pass `Object::make('Test\\Medio')` get namespace from this object

**Comment by gnugat** [comment]
Good catch! I didn't get this issue before, because I've always used a directory in `File`'s filename (e.g. `src/Medio`).
`File#getNamespace` should definitely call `Structure#getNamespace`, and we should get rid of thir awkward login in the constructor.

**Comment by pitpit** [comment]
I didn't see that before I submit this PR: #31 .

**Comment by gnugat** [comment]
Done
