### ISSUE TITLE
Abstract object

### ISSUE THREAD

**Issue by funivan** [memio/memio#35]
If we connect abstract method #22  to object we need validate this behavior

In all cases disable add abstract method to class if class is Final

And there are two behaviors:
- Disable adding abstract method to class if class is not abstract
- Automatically set class as abstract if class contain abstract method

**Comment by gnugat** [comment]
You're right, there's definitely something to do here.
Let's consider the following use case:

``` php
$myMethod = new Method('myMethod');
$myClass = Object::make('Acme\Demo\MyClass')
    ->addMethod($myMethod)
;

$method->makeAbstract();
```

There's no way to know from `Method` if `Object` is already abstract and there's no way to know from `Object` to know if `Method` has been changed to abstract...

Maybe it's time to think about a validation service that could be ran before generating the code? Something like this:

``` php
$myClass = Object::make('Amce\Demo\MyClass')
    ->addMethod(new Method('myMethod'))
;

$validator->validate($object);

echo $prettyPrinter->generateCode($object);
```

What do you think?

**Comment by funivan** [comment]
Possible validator is a good feature)

**Comment by gnugat** [comment]
Done!
