### ISSUE TITLE
Bug with external puli library

### ISSUE THREAD

**Issue by funivan** [memio/memio#41]
When i run this command `./vendor/bin/phpspec run -n -f dot`
a get PHP Notice

```
12:30 ivan medio ❯ ./vendor/bin/phpspec run -n -f dot
PHP Notice:  Constant PULI_FACTORY_CLASS already defined in medio/vendor/autoload.php on line 7
PHP Stack trace:
PHP   1. {main}() medio/vendor/phpspec/phpspec/bin/phpspec:0
PHP   2. require() medio/vendor/phpspec/phpspec/bin/phpspec:15
PHP   3. define() medio/vendor/autoload.php:7

Notice: Constant PULI_FACTORY_CLASS already defined in medio/vendor/autoload.php on line 7

Call Stack:
    0.0001     236768   1. {main}() medio/vendor/phpspec/phpspec/bin/phpspec:0
    0.0017     462392   2. require('medio/vendor/autoload.php') medio/vendor/phpspec/phpspec/bin/phpspec:15
    0.0017     462536   3. define() medio/vendor/autoload.php:7

```

**Comment by gnugat** [comment]
Yes, this is a Puli's bug, see https://github.com/puli/issues/issues/47 (here's a PR to fix it: https://github.com/puli/composer-plugin/pull/11).

Meanwhile, you can work around it be manually editing your `vendor/autoload.php` file like this:

``` php
if (!defined('PULI_FACTORY_CLASS')) {
    // The define statement...
}
```

**Comment by funivan** [comment]
Its a little bit strange to change `vendor/autoload.php` file) 
Possible the best choice is to resolve this issue #33

**Comment by gnugat** [comment]
Yes, I intend to solve #33 before the first Release Candidate, that should definitely fix the issue.

**Comment by gnugat** [comment]
Issue fixed!
