### ISSUE TITLE
Validator

### ISSUE THREAD

**Issue by gnugat** [memio/memio#43]
Create `Gnugat\Medio\Validator`, a service that have 0 to many `Gnugat\Medio\Validator\Constraint` (interface to define) and a `validate` method.
This method takes a Model as argument, finds all the `Constraint` that supports it and execute them. It throws a `InvalidModelException`.

> **Note**: `Validator` should be able to "traverse" the models. For example, if an array of `Method` is given, it should validate the first `Method`, then its first `Argument`, then its second, then the second `Method`, etc.

`InvalidModelException` should have an array of constraint violation messages. Its message should contain all of those.

![UML class diagram](http://yuml.me/723a8e2f)

**Comment by funivan** [comment]
Interesting but here is another solution. 
Create ClasValidator and add some logic.
Check if class is not abstract and contain abstract method.
Possible it is better to create validation list. What exactly we have to validate to make code stable and valid. And then see how to implement validator.

What should do ArgumentValidator ?

**Comment by gnugat** [comment]
Hi @funivan, I think we're talking about the same thing: When `Validator` is complete, I wanted to start creating a `ConcreteObjectMethodsCannotBeAbstract` constraint.

Having a `Validator` service would allow to do many checks in one call, here's a usage example:

``` php
$validator = new Validator();
$validator->addConstraint(new ConcreteObjectMethodsCannotBeAbstract());

$validator->validate(new Object('Gnugat\Medio\MyConcreteClass'));
```

**Comment by gnugat** [comment]
Done!
