### ISSUE TITLE
Decouple from Twig

### ISSUE THREAD

**Issue by webmozart** [memio/memio#51]
I would like to use Medio in Puli, but I would like to avoid pulling in Twig. Is it possible to add a (simple) template backend that uses no external dependencies?

Besides, when do you expect to release a stable version?

**Comment by gnugat** [comment]
Hi @webmozart, I'm glad you like Medio's idea :) .

The first stable version will be released within two weeks (assuming I don't add anything to the initial target). You can follow the progress by checking the "validation" issues.

I've chosen to tie myself to Twig as I wasn't able to implement quickly enough some of its features (filters, includes and whitespace control).
The possibility to decouple Medio from Twig depends on the complexity your request might add, so I'll
need to know more about your use case and how you'd like to use it.

**Comment by webmozart** [comment]
I would like to use Medio to generate Puli's factory class. Simple code generation doesn't do, as I need to construct a model of the factory class and pass it to the event dispatcher, where listeners may add or change methods to the class. So in the end, I need something like (pseudo code):

``` php
$class = new FactoryClass('Puli\GeneratedFactory');
$class->addMethod('getRepository', ...)->setBody(...);
$class->addMethod('getDiscovery', ...)->setBody(...);

// listeners can change and add methods
$dispatcher->dispatchEvent(new GenerateFactoryEvent($class));

$printer->print($class, $file);
```

The result is the factory class you see in the `.puli` directory.

**Comment by gnugat** [comment]
Thanks for the pseudo code snippet, it actually helps a lot.
Currently Medio allows only to describe a class or an interface by adding constants, properties or methods. It is not possible yet to describe a method's body using Models, you'd have to write directly the code in a string:

``` php
$method = Method::make('__construct')
    ->addArgument(new Argument('DateTime', 'createdAt'))
    ->addArgument(new Argument('array', 'options'))

    ->setBody(<<<BODY
    $this->createdAt = $createdAt;
    $this->options = $options;
BODY
);
```

There's also no "dispatcher" available yet, as I was planning to add something similar for version 1.1, but from what I understand you can perfectly rely on your own implementation for now.

I must say that I was kind of hoping that creating a `TemplateEngine` interface and then moving away the Twig implementation, extensions and templates would do the trick, but from the example you gave it appears that you'd need all the current templating features and templates, which is a great deal of work to do.
I might consider to do this myself in the future, but for now I'd like to meet as soon as possible my Minimum Valuable Product, which would allow me to create PHPspec extensions that enhance its generator...
In the list of priorities, there's also the usage of [PHP-parser](https://github.com/nikic/PHP-Parser), allowing to edit existing code.

With that said, if someone showed up and started to work on this, I'd be more than glad to give a hand and merge it :) .

**Comment by webmozart** [comment]
> you'd have to write directly the code in a string

That's fine, I'm taking care of assembling the source code myself.

> There's also no "dispatcher"

I'm using the Symfony Event Dispatcher, I don't need Medio to support that.

> for now I'd like to meet as soon as possible my Minimum Valuable Product

Totally understandable :) I'm going with a handmade least-effort solution then until Medio meets my requirements.

**Comment by gnugat** [comment]
Ok, thanks! Hopefully this shouldn't be too far. I'll leave the issue open for now and I'll come back to it when the time comes.

**Comment by gnugat** [comment]
`memio/pretty-printer` is now decoupled from any Template Engines. Currently, a standalone package (`memio/twig-template-engine`) provides integration with Twig, more can be created in the future but for now I'd like to focus on building stuf with Memio :) .

**Comment by gnugat** [comment]
@webmozart closing as Memio is now decoupled from Twig (although there are no other implementations provided for now)
