### ISSUE TITLE
Gnugat\Medio\Config is missing in composer autoloading + Deprecated installation guidelines

### ISSUE THREAD

**Issue by tigitz** [memio/memio#53]
Hello,

I followed the installation guidelines but ended up with a different version than the given exemple to make it work.

First, when using Path class, there's no namespace available to use it through composer so I updated the PSR-4 autoloader like this :

``` yaml
"autoload": {
        "psr-4": {
            "Gnugat\\Medio\\": "src/Gnugat/Medio",
            "Gnugat\\Medio\\Config\\": "config"
        }
    }
```

Then, with the new addition of Argument model, adding arguments to a Method model require to pass an actual Argument class to the addArgument method, not two strings arguments as actually described.

With some addition of namespaces, I get the following snippet :

``` php
<?php

require __DIR__.'/vendor/autoload.php';

use Gnugat\Medio\Config\Path;
use Gnugat\Medio\PrettyPrinter;
use Gnugat\Medio\Validator;
use Gnugat\Medio\Model\File;
use Gnugat\Medio\Model\Object;
use Gnugat\Medio\Model\Property;
use Gnugat\Medio\Model\Method;
use Gnugat\Medio\Model\Argument;

$loader = new \Twig_Loader_Filesystem(Path::templates());
$twig = new \Twig_Environment($loader);

$prettyPrinter = new PrettyPrinter($twig);

$validate = new Validator();

$file = File::make('src/Gnugat/Medio/MyService.php')
    ->setStructure(Object::make('Gnugat\Medio\MyService')
        ->addProperty(new Property('createdAt'))
        ->addProperty(new Property('filename'))

        ->addMethod(Method::make('__construct')
            ->addArgument(Argument::make('DateTime', 'createdAt'))
            ->addArgument(Argument::make('String', 'filename'))
        )
    )
;

$validate->validate($file);  // @throws Gnugat\Medio\Exception\InvalidModelException

echo $prettyPrinter->generateCode($file);
```

Which is a fully functionnal and straight forward example to get a quick introduction to medio. You just have to "composer require" and paste this example to a php file. Much more clear and quicker. 

On a side note, there's no warning about trying to see the output in a browser. I naievely tried and realise after many refreshes that the output end up commented in a browser (Chrome and Firefox, on Ubuntu). Even if I wrapped it in html tags. I have no quick solution right now for this issue, I tried several different things in the twig templates but I probably didn't dive deep enough to found out how could I make it work. I eventually used cURL.

I made an issue before a possible PR since I might miss something given my actual litlle knowledge on how medio works right now under the hood.

If my improvements seems good enough I could make a PR of it (documentation and composer.json) or just wait till you actually update the necessary files. 

On a second side note, I'm looking forward your generator library to build a quick and fast online ORM designer for doctrine. Might give you ideas for future features ;)

**Comment by gnugat** [comment]
Hi @tigitz,
First of all, thank you very much for going through the trouble of understanding what was wrong with the autoloading and the documentation. Sorry I've missed those points, I'd be really glad if you could create a Pull Request to fix this.

I mainly use the console, it never occured to me that someone would try in a browser. When you say you wrapped the generated code in HTML, was it in `pre` tags? Like this:

``` php
echo '<html><body><pre>';
echo $prettyPrinter->generateCode($file);
echo '</pre><body></html>'
```

I think you're right, the documentation should definitely contain a warning about this.

**Comment by tigitz** [comment]
You're welcome.

About the browser output, despite putting the "right" tags, here's what I got :

![screenshot from 2015-03-22 06 11 56](https://cloud.githubusercontent.com/assets/1524501/6768148/722f6772-d05a-11e4-8e79-e8bb871a8410.png)

I finally understood that it's a matter of escaping the "<" sign of "<?php" which was supposed to be pretty obvious but I missed it.

Anyway, I wrote a note on what you're supposed to do in order to see the ouput in a browser. Might be better to rephrase it as an HTML ouputting instead of a browser outputting. HTML outputting might be usefull to get throught ajax request and embbed in a page or a code editor.

I'm actually wondering if having a strategy pattern on the pretty printer would be a good thing to manage different types of output. 

Something like :

``` php
class PrettyPrinterStrategy {
    private $strategy = NULL; 

    public function __construct($strategy_ind_id) {
        switch ($strategy_ind_id) {
            case "html": 
                $this->strategy = new HTMLPrettyPrinter();
            break;
        }
    }
    public function generateCode($file) {
      return $this->strategy->generateCode($file);
    }
}
```

``` php
class HTMLPrettyPrinter implements PrettyPrinterStrategyInterface {
    public function generateCode($file) {
      return '<pre>'.htmlspecialchars($this->generateCode($file)).'</pre>';
    }
}
```

``` php

$HTMLPrettyPrinter = new PrettyPrinterStrategy('html');

$file = File::make('src/Gnugat/Medio/MyService.php')
    ->setStructure(
        Object::make('Gnugat\Medio\MyService')
            ->addProperty(new Property('createdAt'))
            ->addProperty(new Property('filename'))
            ->addMethod(
                Method::make('__construct')
                    ->addArgument(Argument::make('DateTime', 'createdAt'))
                    ->addArgument(Argument::make('String', 'filename'))
            )
    );

$HTMLPrettyPrinter->generateCode($file);
```

Right now you can achieve the same thing by overiding twig templates and using the `$loader->addPath(__DIR__.'/my-html-templates');`  but there might be use cases where you'll probably need to inject your own logic outside of the template, in the generateCode method for example. Not sure though, can't think about a valid example right now. 

Let me know what you think about it, it's probaly linked with some milestones you've already got. I'll open a new issue to discuss this particular topic if it seems relevant to you @gnugat .

**Comment by gnugat** [comment]
I prefer the idea of the Strategy over having to override all the templates. But maybe we can do something simpler using the Composite Pattern?

``` php
<?php

class HTMLPrettyPrinter
{
    private $prettyPrinter;

    public function __construct(PrettyPrinter $prettyPrinter)
    {
        $this->prettyPrinter = $prettyPrinter;
    }

    public function generateCode($model, array $parameters = array())
    {
        $generatedCode = $this->prettyPrinter->generateCode($model, $parameters);

        return '<pre>'.htmlspecialchars($generatedCode).'</pre>';
    }
}
```

Obviously in both cases we'd need a `PrettyPrinter` interface and break backward compatibility, something I'd like to avoid before v2.

**Comment by gnugat** [comment]
I'll close this ticket since your PR has been merged :)
