### ISSUE TITLE
Create TemplateEngine

### ISSUE THREAD

**Issue by gnugat** [memio/memio#56]
This is the first step to solve @webmozart's request #51 (decouple Medio from Twig).

Create an interface `TemplateEngine`:
- it has paths
- it renders a template by name
- it can give parameters to rendered templates

`PrettyPrinter` would rely on it:

![pretty printer relies on template engine](http://yuml.me/5308d035)

> **Note**: `PrettyPrinter` constructs many `PrettyPrinterStrategies`. It will give them the `TemplateEngine`, they're the ones that actually use it to render templates.

Then create a `TwigTemplateEngine`.

**Comment by funivan** [comment]
Hello @gnugat 
I think about simple code builder interface. 

``` php
interface CodeBuilder {
 public function generateCode(MedioObject $object)
}
```

With implementation of codebuilder you can render (generate code) any medio object (class, interface, arguments, method etc..)
`generateCode` output string 

On top of this you can create template engine which can generate code with different `CodeBuilders` store generated code to file

CodeBuilder is useful for next situation:
1. user want to get string of code from medio object 
2. store them in different places. Temporary files, database, memory ...
3. Easy to implement. Accept medio object - output string. How you implement this logic is your way. 

In Monday I will try to write some pseudo code and attach to this issue for better understanding of my mind.

**Comment by gnugat** [comment]
Hello @funivan
`CodeBuilder` would be the equivalent of the current `PrettyPrinter`?

**Comment by funivan** [comment]
Yes. CodeBuilder is equivalent to PrettyPrinter

**Comment by gnugat** [comment]
Ok :) .

I'd like to keep the name "PrettyPrinter", it refers to [this stackoverflow answer](http://stackoverflow.com/a/5834775/3437428) which explains that there are 2 types of generators: fidelity ones (if you read the code and re generate it, it must be the same) and pretty printer ones (the generated code follows conventions enforced by the generator).

I'd like also to avoid creating empty interfaces like `MedioObject`, we can manage without for now.

The sole purpose of PrettyPrinter is to generate code as a string from a Model description, you can then store the string in a file or print it in a console, etc.
If you want to store something in a database, you'd better store the models directly.

**Comment by gnugat** [comment]
Done!
