### ISSUE TITLE
Create PrettyPrinter in one line

### ISSUE THREAD

**Issue by gnugat** [memio/memio#58]
We want to be able to create a standard (default twig templates) `PrettyPrinter` with one line of code:

``` php
$prettyPrinter = Gnugat\Medio\Config\PrettyPrinter::standard();
```

@tigitz: what do you think about this?

**Comment by tigitz** [comment]
First of all, I probably won't give you a straight answer because after some thinking, our wish of simplifying the required setup to generate the code needs a deeper and proper refactoring imo. I do think that designing a `PrettyPrinter` interface would be the first step  : 

``` php
class PrettyPrinterInterface
{

    function output(){}
}
```

``` php
class TwigPrettyPrinter implements PrettyPrinterInterface
{

    protected $twig;

    private $strategies = array();

    private $templatesPath;

    public function __construct($templatesPath = null)
    {
        $this->templatesPath = $templatesPath !== null ? $templatesPath : __DIR__ . '/../templates';
    }

    function format()
    {
        // Formatting using twig template logic
        $line = new Line();
        $line->add(new ContractLineStrategy());
        $line->add(new FileLineStrategy());
        $line->add(new MethodPhpdocLineStrategy());
        $line->add(new ObjectLineStrategy());
        $line->add(new StructurePhpdocLineStrategy());

        $this->twig->addExtension(new Type());
        $this->twig->addExtension(new Whitespace($line));

        $this->strategies[] = new EmptyCollectionPrettyPrinter();
        $this->strategies[] = new PhpdocCollectionPrettyPrinter($this->twig);
        $this->strategies[] = new ModelCollectionPrettyPrinter($this->twig);
        $this->strategies[] = new PhpdocPrettyPrinter($this->twig);
        $this->strategies[] = new ModelPrettyPrinter($this->twig);


    }

    function output($model, array $parameters = array())
    {

        // Avoid loading twig environment for each output() call
        if (!is_object($this->twig)) {
            $this->setTemplates($this->templatesPath);
        }

        // This makes your formatting logic not loading until you actually want an output of your file
        $this->format();

        foreach ($this->strategies as $strategy) {
            if ($strategy->supports($model, $parameters)) {
                return $strategy->generateCode($model, $parameters);
            }
        }


    }


    function setTemplates($templatesPath)
    {

        $loader = new \Twig_Loader_Filesystem($templatesPath);
        $this->twig = new \Twig_Environment($loader);

    }


}
```

That would give you the flexibility to create every kind of formatting engine including a PHP one mentionned by @webmozart. The only thing you expect from a `PrettyPrinter` is an output which is defined in the interface. Then you would pass this output to a `Generator`. Described like this :

``` php
class GeneratorInterface
{

    function generate(){}
}
```

``` php
abstract class BaseGenerator implements GeneratorInterface
{

    protected $prettyPrinter;

    function __construct(PrettyPrinterInterface $prettyPrinter = null)
    {
        // Load a TwigPrettyPrinter by default
        $this->prettyPrinter = $prettyPrinter !== null ? $prettyPrinter : new TwigPrettyPrinter;
    }

}
```

``` php
class HTMLGenerator extends BaseGenerator
{

    function generate($model, array $parameters = array())
    {

        echo '<html><body><pre>' .
            htmlspecialchars($prettyPrinter->output($model, $parameters)) .
            '</pre></body></html>';
    }
}
```

I Introduced a `Generator` class which is responsible of the way you want to ouput your code. It could be in a php file, in console or in a html file. I understand that you could already add some html tags to the already existing twig templates in your pretty printer but that should be avoided. It's a matter of separation of concerns. You want an object defining your formatting logic and you want an object defining where the output will be displayed.

It would give developpers the possibility to make their own `PrettyPrinter` or `Generator` and mix them with the existing ones for example. 

By default, it provides a Twig formatting engine to all Generator classes that are extending the BaseGenerator.

Giving the following code : 

``` php
$generator = new HTMLGenerator();
// Display a php file formatted using Twig templates and generated wrapped in html tags.
$generator->generate($file);
```

This is the one-liner we were looking for imo, and it could works for a lot of use-cases : 

``` php
// Use a HTML generator using a native PHP formatting logic
$HTMLGenerator = new HTMLGenerator(new PHPPrettyPrinter());

// Use same HTML generator but now with a different PrettyPrinter
$HTMLGenerator->setPrettyPrinter(new TwigPrettyPrinter());

// Use same HTML generator and same PrettyPrinter but now with your custom format defined in your own twig templates
$myOwnTwigPrettyPrinter = new TwigPrettyPrinter()->setTemplates('.../my-own-templates');
$HTMLGenerator->setPrettyPrinter($myOwnTwigPrettyPrinter);

// Use File generator and Twig formatting by default
$FileGenerator = new FileGenerator();

$FileGenerator->generate($file);
```

I might have some typos in my code beacause I didn't test it but I hope you'll get the big picture here. In the end it would make the library respond much more effectively to developpers customization wishes and adding new features.

**Comment by gnugat** [comment]
I think I need to make it clear that "PrettyPrinter" has nothing to do with printing things to the output.
A PrettyPrinter is a code generator that relies on its own styling rules ([I've taken the name from this stackOverflow answer](http://stackoverflow.com/a/5834775/3437428)), it is to be opposed to fidelity printer that would print the exact same code as the given output.

With that said, let's talk about responsibilities:
- the public service would be the code generator (in Medio the name of this class is PrettyPrinter)
- in order to generate code we need a template engine (in Medio we use Twig, but we'd like to be decouple from it by creating a TemplateEngine interface)
- we'd like to be able to print  the generated code to the output, mainly for debug and demos (using `echo` is more than sufficient, no need for classes)
- we'd like to be able to print the generated code to a HTML page (this too doesn't really need a class)
- we'd like to be able to save the generated code in a file (`file_get_contents` is more than enough)

What I'm trying to say here is that `PrettyPrinter` produces a string, this allows for many simple possibilities.

**Comment by tigitz** [comment]
> I think I need to make it clear that "PrettyPrinter" has nothing to do with printing things to the output.

Indeed and that's exactly what my example is trying to prove. Printing things to ouput is the `Generator` responsability. 

It's just a matter of convenience for the end user, if we end up writing docs and tutorials on how you could output things this or that way after using the PrettyPrinter, then why not directly provide utility classes to generalize some use cases and give the developper more tools to use memio ?

I understand it might be out of memio's initial scope and that would be fine if you keep it that way, it's just my opinion that some could share.

If we skip the Generator concept, I would still recommend a PrettyPrinter Interface and create a Composite Pattern to get the following code for the one liner :  

``` php
$prettyPrinter = new TwigPrettyPrinter();
```

Even if memio provides only a single twig implementation as of now, it sets the basic for future template engines. 

If it's too much of a BC-break then I would be ok with your first proposal :)

**Comment by gnugat** [comment]
Well I was considering creating a `PrettyPrinter` interface with a `TwigPrettyPrinter` at first, but since then `PrettyPrinter` got its own logic (generate code for an empty collection, or for a collection, or for a PHPdoc, or for a simple Model).
That's why I'd rather have a `TemplateEngine` interface, used by `PrettyPrinter` with a `TwigTemplateEngine` implementation.

**Comment by tigitz** [comment]
:+1:

**Comment by gnugat** [comment]
Done: `$prettyPrinter = \Memio\Memio\Config\Build::prettyPrinter();`
