### ISSUE TITLE
How to add use statement for importing classes and traits

### ISSUE THREAD

**Issue by rohithmeethal** [memio/memio#62]
Hi, I find the memio really useful for automating boring template generation tasks, one problem I am facing now is there is no way to describe use for classes and traits, any way to implement them ?

**Comment by gnugat** [comment]
Hello, currently Memio can generate interfaces (see Contract model) and classes (see Object model), but not Traits.
It could be possible by adding a new model with the associated templates though.

**Comment by rohithmeethal** [comment]
Hi, I think I didnt eloborate my question, I want to use use statement for clas generation like this

``` php
use Acme\Users\User;// this is missing
use Acme\Billing\Biller;
use Acme\Core\AuthorizationTrait;

class Biller{
       use AuthorizationTrait;// this is missing
}
```

so this is actually about class creating, I wil be trying to solve and sent you pull request if this doesnt actually exist :)

**Comment by rohithmeethal** [comment]
Fully qualified name for the file is available, my bad I just found that, but still couldnt find the same for Object.

**Comment by gnugat** [comment]
Right, I see what you mean now. Use statements are declared by adding FullyQualifiedNames to File, as you've said.
There's nothing yet for trait injection. I'd be glad to review your PR and merge it :) .

**Comment by funivan** [comment]
@rohithmeethal Possible this can help https://github.com/memio/memio/issues/63#issuecomment-104684516
