### ISSUE TITLE
Bug with object extends assign

### ISSUE THREAD

**Issue by funivan** [memio/memio#63]
``` php
<?php
  require 'vendor/autoload.php';

  use Memio\Memio\Config\Build;
  use Memio\Model\File;
  use Memio\Model\Object;

  $tableFile = File::make('src/My/Custom/Generator')
    ->setStructure(
      Object::make('\My\Custom\Generator')
        ->extend(Object::make('\User\TestClass'))
    );

  // Generate the code and display in the console
  $prettyPrinter = Build::prettyPrinter();
  $generatedCode = $prettyPrinter->generateCode($tableFile);
  echo $generatedCode;
```

This configuration generate following code

``` php
<?php
namespace \My\Custom;
class Generator extends TestClass
{
}

```

But i expeect this:

```
<?php

namespace \My\Custom;
use \User\TestClass;

class Generator extends TestClass
{
}

```

I find solution. Just add `addFullyQualifiedName` but how about classes from global namespace?

How to generate this code ?

```
namespace Test;
class User extends \stdClass{}
```

It is a little annoying to add each object to export. Possible it will be better to automatically add all uses in file from structure.  `$file->importAllFqn()`

**Comment by gnugat** [comment]
I'd prefer models to do as less as possible. To fix your issue, you can create a function that will add the use statements, and call it before calling the pretty printer:

``` php
<?php

require 'vendor/autoload.php';

use Memio\Memio\Config\Build;
use Memio\Model\File;
use Memio\Model\Object;

$tableFile = File::make('src/My/Custom/Generator')
    ->setStructure(Object::make('\My\Custom\Generator')
        ->extend(Object::make('\User\TestClass'))
    )
;

function insert_use_statements(File $file) {
    $parent = $file->getStructure()->getParent();
    if (null !== $parent) {
        $file->addFullyQualifiedName($parent->getFullyQualifiedName());
    }
}

insert_use_statements($tableFile);

// Generate the code and display in the console
$prettyPrinter = Build::prettyPrinter();
$generatedCode = $prettyPrinter->generateCode($tableFile);
echo $generatedCode;
```

**Comment by funivan** [comment]
Hello @gnugat. Thanks for help. And here is my last question connected with this behavior. How to extend class from global namespace without exporting them?

``` php
namespace App\CustomTime;
class MyTime extends \DateTime{
}
```

With current behavior we always add `use DateTime`. But our code can be cleaner without this usage.

**Comment by gnugat** [comment]
That's a tricky one. The function that adds use statement could check if the namespace is empty, like this:

``` php
function insert_use_statements(File $file) {
    $parent = $file->getStructure()->getParent();
    if (null === $parent) {
        return;
    }
    $namespace = $parent->getNamespace();
    if (!empty($namespace)) {
        $file->addFullyQualifiedName($parent->getFullyQualifiedName());
    }
}
```

However, the current Twig templates only display the classname, you'd need to create a custom template for this.

**Comment by funivan** [comment]
> However, the current Twig templates only display the classname, you'd need to create a custom template for this.

Ok thanks for fast response =) 

I try to find good solution for this case but it is really hard. It is easy to check in twig template if parent object located in global namespace but how to find if it is exported or not. At the current stage it is easy to always export classes or rewrite twig template and do not export items from global namespace. 

But in future `context` may be a solution. Or probably `namespace context`. In template we can call `$context->getClassName($obect)` and  in code where we create class just this `$file->getContext()->addFullyQualifiedName($object->getFullyQualifiedName())` 
So we can automatically export classes. At current stage we need to make more work to generate classes. Code is not valid. This is just stream of thoughts =)
