### ISSUE TITLE
How to update to already generated code

### ISSUE THREAD

**Issue by dandisy** [memio/memio#70]
How to simple way update (adding other generated code) to already generated code before

**Comment by gnugat** [comment]
Hi @dandisy, unfortunately there's currently nothing out of the box to add more generated code to an existing file.
In [SpecGen](https://github.com/memio/spec-gen/tree/master/src/Memio/SpecGen) I've used [Redaktilo](http://gnugat.github.io/redaktilo/) to edit existing files and add newly generated code, would having a look at SepcGen code help you achieve what you want?

**Comment by funivan** [comment]
Hello. For this task I create library https://github.com/funivan/PhpTokenizer It is based on the top of php tokens
