### ISSUE TITLE
Strategy of class names

### ISSUE THREAD

**Issue by funivan** [memio/memio#71]
Hello. There is one huge strange behaviour when we try to add some class names inside namespaces.
Here is related issue: https://github.com/memio/memio/issues/63
1. Errors inside Full example https://github.com/memio/memio
   Generated code contain error. `DateTime` class is not found and I thinks this can confuse some users
2. When we add some `class references` or `class fqn` to the class we should implement logic for exporting them. It is a little bit annoying. 
   Adding arguments, properties, implementations, extends, phpdocs. All this actions require to write some custom function on "How to export reference class to this object"

One of the features that I propose is generate code without exporting any classes. 
Plus add function to export class references from our structure

We  can introduce new structure "ClassRefrerence"  and pass it to any `defaultValues`.

``` php

  \Memio\Model\Object::make('Vendor\My\Cache')
    ->extend(\Memio\Model\Object::make('Vendor\My\CacheInterface'))
    ->addProperty(
      (new \Memio\Model\Property("provider"))
        ->setDefaultValue(new ClassReference('Vendor\My\Prociders\Redis'))
    );

```

Output

``` php
nespace Vendor\My;
 class Cache extends \Vendor\My\CacheInterface {
     private $provider = \Vendor\My\Prociders\Redis::class;
 }
```

Example 2

``` php
$method = Method::make('__construct')
    ->addArgument(new Argument(new ClassReference('\\DateTime'), 'createdAt'));
```

Output

``` php
public function __construct(\DateTime $createdAt){

}
```

Next we can add auto import function, witch accept file. This function can find properties, arguments and etc. Detect class structures and export them. 

**I had implement some fixes for this issue but it is very annoying to fix some new bugs every time. I need to write some layer on top of the `Memio` for generating code in nice manner.**

@gnugat How do you thinks can this issue be resolved inside the core of this library. I can make PR if it is interesting for your.

**Comment by gnugat** [comment]
Hi @funivan, to fix the issue with `DateTime` on the example we can find in the `README.md`, we simply need to add a use statement:

``` php
<?php

require __DIR__.'/vendor/autoload.php';

use Memio\Memio\Config\Build;
use Memio\Model\File;
use Memio\Model\Object;
use Memio\Model\Property;
use Memio\Model\Method;
use Memio\Model\Argument;

// Describe the code you want to generate using "Models"
$file = File::make('src/Vendor/Project/MyService.php')
    ->addFullyQualifiedName('DateTime')
    ->setStructure(
        Object::make('Vendor\Project\MyService')
            ->addProperty(new Property('createdAt'))
            ->addProperty(new Property('filename'))
            ->addMethod(
                Method::make('__construct')
                    ->addArgument(new Argument('DateTime', 'createdAt'))
                    ->addArgument(new Argument('string', 'filename'))
            )
    )
;
```

> **Note**: the `->addFullyQualifiedName('DateTime')` call will generate a `use DateTime;` line that fixes the issue.

Regardless, I understand how you feel regarding this lack of feature coming from Memio.
Unfortunately, this is an intended behaviour: Memio should really be seen as a low level library allowing you to generate code. Any features that allow shortcut (e.g. add automatically use statements) are higher level and belong in a separate library.

This is how it's done in [SpecGen](https://github.com/memio/spec-gen/tree/master/src/Memio/SpecGen) for example: it adds a layer on top of Memio to generate code in a highly opinionated way (e.g. automatically add a property for each arguments of the generated constructor).

**Comment by funivan** [comment]
>  Any features that allow shortcut (e.g. add automatically use statements) are higher level and belong in a separate library.

Ok, I understand. But how about disable autoimport. When we call

``` php
 Method::make('__construct')
                    ->addArgument(new Argument('\My\Custom\DateTime', 'createdAt'))
```

The memio can generate 

``` php
public function __construct(\My\Custom\DateTime $createdAt){
}
```

Why memio try to detect fqn and use only name ? Thanks)

**Comment by gnugat** [comment]
That's the default coding style (this view logic for this is done in [a template](https://github.com/memio/twig-template-engine/blob/master/templates/argument.twig)).

Memio was created with the possibility to choose the coding style you want: if the default one doesn't fit your need, then you can create a template to override it.

**Comment by funivan** [comment]
Ok thanks for help :)
