### ISSUE TITLE
Adding code anywhere around class

### ISSUE THREAD

**Issue by gnud** [memio/memio#72]
Is there a way to use this syntax: defined( 'MYVAR') or die('bla bla');

One of these ways is acceptable :) :
 1) Injecting a string with the code at given point in the file.
 2) Creating a construct for conditions

Thanks.

**Comment by gnud** [comment]
I solved the problem by using custom file templates:
$prettyPrinter->addTemplatePath(**DIR**.'/my_templates');

**Comment by gnugat** [comment]
That's good to know, thanks for coming back with your solution :)
